export const DEGUSTATOR_LOGGED = "DEGUSTATOR_LOGGED";

export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
<<<<<<< HEAD
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
=======
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
>>>>>>> 272dc2b75321a01b36985dc9559f786937f7dfbe

export const DEGUSTATOR_PRESS_BTN = "DEGUSTATOR_PRESS_BTN";
export const DEGUSTATOR_SUM = "DEGUSTATOR_SUM";
export const WINE_ELIMINATE = "WINE_ELIMINATE";
export const WINE_ID = "WINE_ID";
export const DEGUSTATOR_COMMENT = "DEGUSTATOR_COMMENT";

export const RESULTS_SEND_INIT = "RESULTS_SEND_INIT";
export const RESULTS_SEND_START = "RESULTS_SEND_START";
export const RESULTS_SEND_FAIL = "RESULTS_SEND_FAIL";
export const RESULTS_SEND_SUCCESS = "RESULTS_SEND_SUCCESS";
export const RESULTS_SEND_CANCELED = "RESULTS_SEN_CANCELED";

export const RESET_RESULTS = "RESET_RESULTS";

export const ADD_WINE_START = "ADD_WINE_START";
export const ADD_WINE_FAIL = "ADD_WINE_FAIL";
export const ADD_WINE_SUCCES = "ADD_WINE_SUCCES";

export const EDIT_WINE = "EDIT_WINE";

export const SAVE_EDIT_WINE_START = "SAVE_EDIT_WINE_START";
export const SAVE_EDIT_WINE_SUCCES = "SAVE_EDIT_WINE_SUCCES";
export const SAVE_EDIT_WINE_FAIL = "SAVE_EDIT_WINE_FAIL"

export const DELETE_WINE_START = "DELETE_WINE_START";
export const DELETE_WINE_SUCCES = "DELETE_WINE_SUCCES";
export const DELETE_WINE_FAIL = "DELETE_WINE_FAIL";

export const FETCH_WINE_LIST_START = "FETCH_WINE_LIST_START";
export const FETCH_WINE_LIST_SUCCES = "FETCH_WINE_LIST_SUCCES";
export const FETCH_WINE_LIST_FAIL = "FETCH_WINE_LIST_FAIL";

export const SORT_WINE_BY = "SORT_WINE_BY";

export const DATABASE_DELETE_INIT = "DATABASE_DELETE_INIT";
export const DATABASE_DELETE_START = "DATABASE_DELETE_START";
export const DATABASE_DELETE_SUCCES = "DATABASE_DELETE_SUCCES";
export const DATABASE_DELETE_FAIL = "DATABASE_DELETE_FAIL";

export const DATABASE_IMPORT_INIT = "DATABASE_IMPORT_INIT";
export const DATABASE_IMPORT_START = "DATABASE_IMPORT_START";
export const DATABASE_IMPORT_SUCCES = "DATABASE_IMPORT_SUCCES";
export const DATABASE_IMOPORT_FAIL = "DATABASE_IMOPORT_FAIL";

export const ADD_DEGUSTATOR_START = "ADD_DEGUSTATOR_START";
export const ADD_DEGUSTATOR_SUCCES = "ADD_DEGUSTATOR_SUCCES";
export const ADD_DEGUSTATOR_FAIL = "ADD_DEGUSTATOR_FAIL";

export const DATABASE_DEG_DELETE_INIT = "DATABASE_DEG_DELETE_INIT";
export const DATABASE_DEG_DELETE_CANCELED = "DATABASE_DEG_DELETE_CANCELED";
export const DATABASE_DEG_DELETE_START = "DATABASE_DEG_DELETE_START";
export const DATABASE_DEG_DELETE_SUCCES = "DATABASE_DEG_DELETE_SUCCES";
export const DATABASE_DEG_DELETE_FAIL = "DATABASE_DEG_DELETE_FAIL";

export const DATABASE_DEG_IMPORT_INIT = "DATABASE_DEG_IMPORT_INIT";
export const DATABASE_DEG_IMPORT_CANCELED = "DATABASE_DEG_IMPORT_CANCELED";
export const DATABASE_DEG_IMPORT_START = "DATABASE_DEG_IMPORT_START";
export const DATABASE_DEG_IMPORT_SUCCES = "DATABASE_DEG_IMPORT_SUCCES";
export const DATABASE_DEG_IMPORT_FAIL = "DATABASE_DEG_IMPORT_FAIL";

export const FETCH_DEGLIST_START = "FETCH_DEGLIST_START";
export const FETCH_DEGLIST_SUCCES = "FETCH_DEGLIST_SUCCES";
export const FETCH_DEGLIST_FAIL = "FETCH_DEGLIST_FAIL";

export const SORT_DEG_BY = "SORT_DEG_BY";

export const EDIT_DEG = "EDIT_DEG";

export const SAVE_EDIT_DEG_START = "SAVE_EDIT_DEG_START";
export const SAVE_EDIT_DEG_SUCCES = "SAVE_EDIT_DEG_SUCCES";
export const SAVE_EDIT_DEG_FAIL = "SAVE_EDIT_DEG_FAIL";

export const DELETE_DEG_INIT = "DELETE_DEG_INIT";
export const DELETE_DEG_CANCELED = "DELETE_DEG_CANCELED";
export const DELETE_DEG_START = "DELETE_DEG_START";
export const DELETE_DEG_SUCCES = "DELETE_DEG_SUCCES";
export const DELETE_DEG_FAIL = "DELETE_DEG_FAIL";

export const CREATE_DEG_GROUPS = "CREATE_DEG_GROUPS";

export const MINIMALISED_DEG_GROUPS = "MINIMALISED_DEG_GROUPS";

export const FETCH_DEGLIST_GROUP_START = "FETCH_DEGLIST_GROUP_START";
export const FETCH_DEGLIST_GROUP_SUCCES = "FETCH_DEGLIST_GROUP_SUCCES";
export const FETCH_DEGLIST_GROUP_FAIL = "FETCH_DEGLIST_GROUP_FAIL";

export const SAVE_DEG_GROUPS_START = "SAVE_DEG_GROUPS_START";
export const SAVE_DEG_GROUPS_SUCCES = "SAVE_DEG_GROUPS_SUCCES";
export const SAVE_DEG_GROUPS_FAIL = "SAVE_DEG_GROUPS_FAIL";

export const DRAG_DEG_FROM_LIST = "DRAG_DEG_FROM_LIST";
export const DROP_DEG_TO_GROUP = "DROP_DEG_TO_GROUP";
export const DRAG_DEG_FROM_GROUP = "DRAG_DEG_FROM_GROUP";

export const FETCH_DEG_GROUPS_START = "FETCH_DEG_GROUPS_START";
export const FETCH_DEG_GROUPS_SUCCES = "FETCH_DEG_GROUPS_SUCCES";
export const FETCH_DEG_GROUPS_FAIL = "FETCH_DEG_GROUPS_FAIL";

export const DELETE_GROUPS_INIT = 'DELETE_GROUPS_INIT';
export const DELETE_GROUPS_CANCELED = "DELETE_GROUPS_CANCELED";
export const DELETE_GROUPS_START = "DELETE_GROUPS_START";
export const DELETE_GROUPS_SUCCES = "DELETE_GROUPS_SUCCES";
export const DELETE_GROUPS_FAIL = "DELETE_GROUPS_FAIL";

export const FETCH_WINE_INFO_START = "FETCH_WINE_INFO_START";
export const FETCH_WINE_INFO_SUCCES = "FETCH_WINE_INFO_SUCCES";
export const FETCH_WINE_INFO_FAIL = "FETCH_WINE_INFO_FAIL";